<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2w4ecv3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2w4ecv3/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2w4ecv3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2w4ecv3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2w4ecv3\appProdProjectContainer([
    'container.build_hash' => '2w4ecv3',
    'container.build_id' => 'b7244557',
    'container.build_time' => 1587029601,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2w4ecv3');
